### ISSUE TITLE
Allow to suppress SSL warnings

### ISSUE THREAD

**Issue by klepikov** [andrewf/pcap2har#20]
SSL is work in progress, and these warnings do not indicate a problem with the captured traffic -- they are just an indication of an incomplete decoding implementation, as far as I understand. As such, they clutter the output, while the user cannot do anything with their captured traffic to "fix" these warnings. It would therefore be good to allow to suppress them, or even suppress them by default, until the SSL decoding works well enough to support common cases.

> WARNING:root:Unknown cipher suite code 0xc011
> WARNING:root:Blackholing SSL/TLS flow due to error: SSL3Exception('Unknown
> or invalid handshake type 72',)
> WARNING:root:Unknown cipher suite code 0xc011
> WARNING:root:Blackholing SSL/TLS flow due to error: SSL3Exception('Unknown
> or invalid handshake type 38',)
> WARNING:root:Unknown cipher suite code 0xc011

**Comment by andrewf** [comment]
It's probably better to just turn SSL off in the settings.

**Comment by klepikov** [comment]
Yeah makes sense, thanks.
